-- V71: Add agreement terms template to facility_settings
-- This stores the default T&C text that gets embedded into agreement PDFs

ALTER TABLE facility_settings
ADD COLUMN IF NOT EXISTS agreement_terms_template TEXT;

-- Seed a sensible default for existing facilities
UPDATE facility_settings
SET agreement_terms_template = E'1. The CBWTF agrees to collect, transport, and dispose of bio-medical waste generated by the HCF in accordance with the Bio-Medical Waste Management Rules, 2016 and subsequent amendments.\n\n2. The HCF shall segregate bio-medical waste at the point of generation into the prescribed color-coded categories (Yellow, Red, Blue, White) as per CPCB guidelines.\n\n3. The CBWTF shall provide collection services as per the mutually agreed schedule. Any changes to the schedule must be communicated at least 48 hours in advance.\n\n4. The HCF shall ensure that bio-medical waste is stored in designated areas and is handed over to the CBWTF collection staff in properly sealed, labeled bags/containers.\n\n5. The billing shall be computed based on the agreed rate structure. Invoices will be generated monthly and payment is due within the grace period specified by the CBWTF.\n\n6. Both parties shall maintain records of waste collected, transported, and disposed of, and shall make such records available for inspection by regulatory authorities.\n\n7. The CBWTF shall issue a certificate of disposal/treatment to the HCF on a monthly basis.\n\n8. Either party may terminate this agreement by providing 30 days written notice. Outstanding dues, if any, must be cleared before termination.\n\n9. Any dispute arising out of this agreement shall be resolved through mutual consultation. If unresolved, disputes shall be referred to the jurisdictional authority.\n\n10. This agreement is subject to the provisions of the Bio-Medical Waste Management Rules, 2016, and any amendments thereof.'
WHERE agreement_terms_template IS NULL;
