package com.smartcbwtf.controller;

import com.smartcbwtf.config.TenantContext;
import com.smartcbwtf.domain.AnnualComplianceReport;
import com.smartcbwtf.domain.Facility;
import com.smartcbwtf.repository.AnnualComplianceReportRepository;
import com.smartcbwtf.repository.BarcodeComplianceReportRepository;
import com.smartcbwtf.repository.DailyComplianceReportRepository;
import com.smartcbwtf.repository.MonthlyComplianceReportRepository;
import com.smartcbwtf.repository.ViolationReportRepository;
import com.smartcbwtf.service.ComplianceReportExportService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.bind.annotation.PostMapping;

import java.time.Instant;
import java.util.Arrays;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class ComplianceReportControllerSecurityTest {

    @Mock
    private DailyComplianceReportRepository dailyReportRepository;
    @Mock
    private MonthlyComplianceReportRepository monthlyReportRepository;
    @Mock
    private AnnualComplianceReportRepository annualReportRepository;
    @Mock
    private BarcodeComplianceReportRepository barcodeReportRepository;
    @Mock
    private ViolationReportRepository violationReportRepository;
    @Mock
    private ComplianceReportExportService reportExportService;

    private ComplianceReportController controller;
    private UUID facilityId;

    @BeforeEach
    void setUp() {
        controller = new ComplianceReportController(
                dailyReportRepository,
                monthlyReportRepository,
                annualReportRepository,
                barcodeReportRepository,
                violationReportRepository,
                reportExportService);
        facilityId = UUID.randomUUID();
        TenantContext.set(new TenantContext.TenantInfo(UUID.randomUUID(), facilityId, null,
                "CBWTF_ADMIN", "admin"));
    }

    @AfterEach
    void tearDown() {
        TenantContext.clear();
    }

    @Test
    void complianceReportControllerRemainsReadOnly() {
        boolean hasPostEndpoint = Arrays.stream(ComplianceReportController.class.getDeclaredMethods())
                .anyMatch(method -> method.isAnnotationPresent(PostMapping.class));

        assertFalse(hasPostEndpoint, "Compliance reports are generated by scheduled jobs, not ad-hoc API calls");
    }

    @Test
    void dailyReportDetailUsesTenantScopedLookup() {
        UUID reportId = UUID.randomUUID();
        when(dailyReportRepository.findByIdAndFacilityId(reportId, facilityId)).thenReturn(Optional.empty());

        var response = controller.getDailyReport(reportId);

        assertEquals(404, response.getStatusCode().value());
        verify(dailyReportRepository).findByIdAndFacilityId(reportId, facilityId);
        verify(dailyReportRepository, never()).findById(reportId);
    }

    @Test
    void dailyPdfUsesTenantScopedLookupBeforeExport() {
        UUID reportId = UUID.randomUUID();
        when(dailyReportRepository.findByIdAndFacilityId(reportId, facilityId)).thenReturn(Optional.empty());

        var response = controller.downloadDailyReportPdf(reportId);

        assertEquals(404, response.getStatusCode().value());
        verify(dailyReportRepository).findByIdAndFacilityId(reportId, facilityId);
        verify(dailyReportRepository, never()).findById(reportId);
        verifyNoInteractions(reportExportService);
    }

    @Test
    void monthlyPdfUsesTenantScopedLookupBeforeExport() {
        UUID reportId = UUID.randomUUID();
        when(monthlyReportRepository.findByIdAndFacilityId(reportId, facilityId)).thenReturn(Optional.empty());

        var response = controller.downloadMonthlyReportPdf(reportId);

        assertEquals(404, response.getStatusCode().value());
        verify(monthlyReportRepository).findByIdAndFacilityId(reportId, facilityId);
        verify(monthlyReportRepository, never()).findById(reportId);
        verifyNoInteractions(reportExportService);
    }

    @Test
    void annualPdfUsesTenantScopedLookupBeforeExport() {
        UUID reportId = UUID.randomUUID();
        when(annualReportRepository.findByIdAndFacilityId(reportId, facilityId)).thenReturn(Optional.empty());

        var response = controller.downloadAnnualReportPdf(reportId);

        assertEquals(404, response.getStatusCode().value());
        verify(annualReportRepository).findByIdAndFacilityId(reportId, facilityId);
        verify(annualReportRepository, never()).findById(reportId);
        verifyNoInteractions(reportExportService);
    }

    @Test
    void annualExcelUsesTenantScopedLookup() {
        UUID reportId = UUID.randomUUID();
        when(annualReportRepository.findByIdAndFacilityId(reportId, facilityId)).thenReturn(Optional.empty());

        var response = controller.downloadAnnualReportExcel(reportId);

        assertEquals(404, response.getStatusCode().value());
        verify(annualReportRepository).findByIdAndFacilityId(reportId, facilityId);
        verify(annualReportRepository, never()).findById(reportId);
        verifyNoInteractions(reportExportService);
    }

    @Test
    void annualExcelBackfillsMissingWorkbookForExistingReport() {
        AnnualComplianceReport report = annualReport();
        byte[] excel = new byte[] { 1, 2, 3 };
        when(annualReportRepository.findByIdAndFacilityId(report.getId(), facilityId)).thenReturn(Optional.of(report));
        when(reportExportService.annualExcel(report)).thenReturn(excel);

        var response = controller.downloadAnnualReportExcel(report.getId());

        assertEquals(200, response.getStatusCode().value());
        assertArrayEquals(excel, response.getBody());
        assertEquals("no-store", response.getHeaders().getCacheControl());
        verify(reportExportService).annualExcel(report);
        verify(annualReportRepository).save(report);
    }

    @Test
    void annualPdfDownloadUsesNoStoreCacheHeader() {
        AnnualComplianceReport report = annualReport();
        byte[] pdf = new byte[] { 4, 5, 6 };
        report.setPdfBytes(pdf);
        when(annualReportRepository.findByIdAndFacilityId(report.getId(), facilityId)).thenReturn(Optional.of(report));

        var response = controller.downloadAnnualReportPdf(report.getId());

        assertEquals(200, response.getStatusCode().value());
        assertArrayEquals(pdf, response.getBody());
        assertEquals("no-store", response.getHeaders().getCacheControl());
    }

    @Test
    void barcodePdfUsesTenantScopedLookupBeforeExport() {
        UUID reportId = UUID.randomUUID();
        when(barcodeReportRepository.findByIdAndFacilityId(reportId, facilityId)).thenReturn(Optional.empty());

        var response = controller.downloadBarcodeReportPdf(reportId);

        assertEquals(404, response.getStatusCode().value());
        verify(barcodeReportRepository).findByIdAndFacilityId(reportId, facilityId);
        verify(barcodeReportRepository, never()).findById(reportId);
        verifyNoInteractions(reportExportService);
    }

    @Test
    void violationPdfUsesTenantScopedLookupBeforeExport() {
        UUID reportId = UUID.randomUUID();
        when(violationReportRepository.findByIdAndFacilityId(reportId, facilityId)).thenReturn(Optional.empty());

        var response = controller.downloadViolationReportPdf(reportId);

        assertEquals(404, response.getStatusCode().value());
        verify(violationReportRepository).findByIdAndFacilityId(reportId, facilityId);
        verify(violationReportRepository, never()).findById(reportId);
        verifyNoInteractions(reportExportService);
    }

    private AnnualComplianceReport annualReport() {
        Facility facility = new Facility();
        facility.setId(facilityId);
        facility.setName("Facility");

        AnnualComplianceReport report = new AnnualComplianceReport();
        report.setId(UUID.randomUUID());
        report.setFacility(facility);
        report.setFinancialYear("2025-26");
        report.setGeneratedAt(Instant.parse("2026-04-01T01:00:00Z"));
        report.setStatus(AnnualComplianceReport.Status.READY);
        report.setDataCompleteness(AnnualComplianceReport.DataCompleteness.COMPLETE);
        report.setSourceWindowFrom(Instant.parse("2025-03-31T18:30:00Z"));
        report.setSourceWindowTo(Instant.parse("2026-03-31T18:30:00Z"));
        report.setDataJson("{}");
        report.setChecksum("abc123");
        return report;
    }
}
